services:
    postgres:
        image: postgres:16
        container_name: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: appdb
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - TaskFlow

volumes:
    postgres_data:

networks:
    TaskFlow:
        name: TaskFlow
        driver: bridge
